# Generated by Django 4.1.7 on 2023-04-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_cloth_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth_tbl',
            name='Photo',
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cloth_idx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weatherApp.cloth_tbl')),
            ],
        ),
    ]
